### ISSUE TITLE
Certain special characters are not correctly escaped in the API request URLs

### ISSUE THREAD

**Issue by overcast07** [MJ-014/Wiki-Shared-Item-Obtainer#1]
Currently, if you want to use a category with an ampersand in its name, e.g. "M&M", you have to escape it yourself (i.e. "M%26M"). This workaround is not particularly obvious, so it would be preferable if this was just handled automatically, for usability purposes.

I don't know if this is the only case of a character not being properly escaped.

**Comment by MJ-014** [comment]
Thanks for pointing this issue out. I've updated the script.
